#!/usr/bin/env python3
import smtplib
import sys


def main():
    try:
        from dns import resolver
    except ImportError:
        resolver = None
        return 'dnspython not installed, use `pip install dnspython`'

    if len(sys.argv) != 2:
        return 'wrong number of arguments, please provide email address'

    email = sys.argv[1]
    mailbox, host = email.split('@', 1)

    answers = sorted(resolver.query(host, 'MX'), key=lambda r: r.preference)
    print(answers)
    mx_host = answers[0].exchange.to_text()

    print('connecting to mail server "{}"...'.format(mx_host))
    with smtplib.SMTP(mx_host, 0) as smtp:
        print('noop:', smtp.noop())
        print('helo:', smtp.helo())
        print('mail:', smtp.mail('mail-server-test@example.com'))
        print('rcpt:', smtp.rcpt(email))


if __name__ == '__main__':
    err = main()
    if err:
        print(err, file=sys.stderr)
        sys.exit(1)
